### ISSUE TITLE
"Error: Cannot find module 'launchpad-module'"

### ISSUE THREAD

**Issue by leovanhaaren** [apollographql/launchpad#94]
I get this error since the last few hours. It might be related to;
https://github.com/apollographql/launchpad/commit/26803d6ae3de90788e8a33f82ca3e2821d5c0e92

```{
  "code": 400,
  "error": "Script returned an error.",
  "details": "Error: Cannot find module 'launchpad-module'",
  "name": "Error",
  "message": "Cannot find module 'launchpad-module'",
  "stack": "Error: Cannot find module 'launchpad-module'\n    at Function.Module._resolveFilename (module.js:325:15)\n    at Function.WebtaskModule._resolveFilename (/data/sandbox/lib/module.js:25:27)\n    at WebtaskModule.require (/data/sandbox/lib/module.js:101:39)\n    at require (/data/sandbox/lib/module.js:136:21)\n    at Object.<anonymous> (/data/io/7f6e0618-5857-4352-a891-ca24a0492a8f/webtask.js:21:21)\n    at WebtaskModule.compileWebtask (/data/sandbox/lib/module.js:95:34)\n    at defaultJavascriptCompiler (/data/sandbox/lib/compiler.js:119:30)\n    at defaultCompiler (/data/sandbox/lib/compiler.js:128:16)\n    at /data/sandbox/lib/compiler.js:231:17\n    at /data/sandbox/node_modules/async/dist/async.js:3866:24"

**Comment by abernix** [comment]
@leovanhaaren We believe this should be working again at the present moment and @evans is investigating (though your suspicion is relatively accurate!).

**Comment by geostokes** [comment]
I am seeing something that seems sort of related to this as well. I received this error at first however now I am getting a duplicate dependency error and in the npm deps 'graphql-tools' is defined twice.

Here is my error:
`"message": "Cannot use GraphQLNonNull \"[RenewalBatch!]!\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results."`

**Comment by evans** [comment]
@leovanhaaren and @geostokes Thank you for flagging and confirming the issue! Completely my fault 🤦‍♂️ . It should work now. Please let me know if you run into any more issues!

**Comment by leovanhaaren** [comment]
Thanks for fixing this! @evans
