### ISSUE TITLE
Error Message: Multiple Instances of GraphQL

### ISSUE THREAD

**Issue by seeschweiler** [apollographql/launchpad#95]
Running a nested query like

`query PostsAndUser {
  post(id: 1) {
    id
    title
    user {
      name
      posts {
        id
      }
    }
  }
}`

returns the following error message:

Cannot use GraphQLList \"[Post]\" from another module or realm.\n\nEnsure that there is only one instance of \"graphql\" in the node_modules\ndirectory. If different versions of \"graphql\" are the dependencies of other\nrelied on modules, use \"resolutions\" to ensure only one version is installed.\n\nhttps://yarnpkg.com/en/docs/selective-version-resolutions\n\nDuplicate \"graphql\" modules cannot be used at the same time since different\nversions may have different capabilities and behavior. The data from one\nversion used in the function from another could produce confusing and\nspurious results.

**Comment by Saeris** [comment]
This has also been happening with my project since Thursday morning this week. Looking at `npm deps` does indeed show multiple copies of `graphql-tools` and downloading the pad similarly shows duplicate entries in `package.json`.

Here's my pad for reference:

https://launchpad.graphql.com/lk3jvvvjnq

**Comment by seeschweiler** [comment]
Here is my pad for reference to:

https://launchpad.graphql.com/nxz11n90q7

It's also happing when I fork the pad https://launchpad.graphql.com/1jzxrj179 from the Readme.md documentation.

**Comment by seeschweiler** [comment]
@Saeris Yes, same for me. Looking in `npm deps` shows that `graphql-tools` is listed twice which different versions

**Comment by ilabacheuski** [comment]
[Example for falling on NonNullable types](https://launchpad.graphql.com/4r88j8pnn9)
All fields, that are marked with GraphQLNonNullable use two separate `graphql-tools` libraries and cannot be queried.
Just add a password field to query to see how it happens.

![image](https://user-images.githubusercontent.com/10571879/38078774-03b6b00a-3346-11e8-9a46-76ea32de30c6.png)

**Comment by evans** [comment]
@seeschweiler Thank you for flagging the issue!

Really apologize about the problems. You should be able to make a modification to your code and save, which will refresh the backing webtask. Let me know if you run into the issue again.

**Comment by Saeris** [comment]
@evans Following your recommendation I made changes to my pad's code, clicked save, and I'm still getting errors. There's still two instances of `graphql-tools@2.15.0`, and I get the following error in the graphiql output:

`SyntaxError: Unexpected token < in JSON at position 0`

And this error in the logs when I try to run a query:

```shell
Error: cannot use graphqlschema "[object object]" from another module or realm.

ensure that there is only one instance of "graphql" in the node_modules
directory. if different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. the data from one
version used in the function from another could produce confusing and
spurious results.
at instanceof (/data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/graphql/jsutils/instanceof.js:17:13)
at isschema (/data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/graphql/type/schema.js:48:35)
at validateschema (/data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/graphql/type/validate.js:51:25)
at assertvalidschema (/data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/graphql/type/validate.js:76:16)
at object.validate (/data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/graphql/validation/validate.js:61:35)
at dorunquery (/data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runquery.js:88:38)
at /data/_verquire/launchpad-module/0.0.0/node_modules/launchpad-module/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runquery.js:22:54
at process._tickdomaincallback (node.js:481:9)
```

I'm not sure what changes I would need to make. Typically only adding a space is enough for launchpad to think my code is different and allows me to save it again. This was the error I received originally when I first ran into this problem.

Since I've got my API working elsewhere now, I don't really need my pad to work again, but I thought you'd like to know anyway.

Here's a link to the pad in question again for you to check out:

https://launchpad.graphql.com/lk3jvvvjnq
